### ISSUE TITLE
Place storage backends behind feature flags

### ISSUE THREAD

**Issue by ok300** [cashubtc/cdk#511]
Right now, to implement a wallet one needs to import the CDK and the chosen storage backend crate

```toml
cdk = { version = "v0.6.0", features = ["wallet"] }
cdk-sqlite = { version = "v0.6.0", features = ["wallet"] }
```

`mintd` has a dependency to all storage backends.

It would be simpler at least for wallet implementors to be able to choose the storage backend via a feature flag:

```toml
cdk = { version = "v0.6.0", features = ["wallet", "sqlite"] }
```
