### ISSUE TITLE
Error "Cannot convert units" when using USD backend

### ISSUE THREAD

**Issue by gudnuf** [cashubtc/cdk#838]
When trying to get a melt quote for unit `usd` "Cannot convert units" is thrown. From what I can tell, melting units that require an exchange rate is currently not possible.

 The call ([here](https://github.com/cashubtc/cdk/blob/896b1dfa5f75d1d4d216f47adeb0240718981439/crates/cdk/src/mint/melt.rs#L113)) to convert the invoice amount into the request unit seems to be the problem. The [`to_unit`](https://github.com/cashubtc/cdk/blob/896b1dfa5f75d1d4d216f47adeb0240718981439/crates/cashu/src/amount.rs#L283) method does not support going from msat to usd.

The problem is that we need a BTC/USD exchange rate to do this.

## To reproduce

Usinf the following config I minted usd tokens then made a request to get a melt quote for unit `usd` at `/v1/melt/quote/bolt11`:

```toml
[info]
url = "http://127.0.0.1:8085"
listen_host = "127.0.0.1"
listen_port = 8085
mnemonic = "naive submit trim pipe reform adult genuine dream start custom truth churn"

[mint_info]
name = "My Mint"
description = "A Cashu mint"

[database]
engine = "sqlite"

[ln]
ln_backend = "fakewallet"
min_mint = 1
max_mint = 500000
min_melt = 1
max_melt = 500000

[fake_wallet]
supported_units = ["sat", "usd"]
fee_percent = 0.02
reserve_fee_min = 1
min_delay_time = 1
max_delay_time = 3
```

Example request body to get melt quote:
```json
{"unit":"usd","request":"lnbc90n1p59kdu4pp5n4azwuzg5emwgwu78g80vxhw0ymkvsyw7k9v956m0mvfvyaqf59shp58t66xgwpxwvnf5knxqsff7spkklncuyrcql4uma22ynca3jhq26scqzzsxqyz5vqsp5eqf0ue8p8agvr30ecm5zf4pcc3kn3ycvx6gfa3hea6xlackygaxq9qxpqysgqejlrzvwy97p6ah2u3qfm7zyx96ky2m2p8pnut3l6vq7g598tqsg9h93fd5hapwuu6vkaush9g65k58aqkzckmgl5sf0xnmj2gkugk4gpgf9gxv"}
```
